- name: Find existing emr-api omod
  find:
    paths: /opt/openmrs/modules
    patterns: emrapi-omod*.omod
  register: result

- name: Delete emr-api omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get emr-api omod from s3 bucket and place it in /opt/openmrs/modules
  get_url:
    url: "{{ emr_api_omod }}"
    dest: /opt/openmrs/modules/
    mode: 0644
    owner: bahmni
    group: bahmni
