set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Type of pain","Type of pain","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Assessment of vital signs","Assessment of vital signs","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Associated feature","Associated feature","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Burning","Burning","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Cause of Injury","Cause of Injury","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Currently taking medication","Currently taking medication","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Electrical Shocks","Electrical Shocks","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Functional status on arrival","Functional status on arrival","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Gait training","Gait training","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, History of Allergy","History of Allergy","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Hypoaesthesia to pinprick","Hypoaesthesia to pinprick","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Hypoaesthesia to touch","Hypoaesthesia to touch","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Itching","Itching","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Light brushing","Light brushing","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Main Diagnosis (surgical)","Main Diagnosis (surgical)","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Medical Diagnoses (if any)","Medical Diagnoses (if any)","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Mobility and strengthening exercises?","Mobility and strengthening exercises?","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Numbness","Numbness","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Pain","Pain","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Painful cold","Painful cold","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Past Medical History","Past Medical History","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Past surgical history","Past surgical history","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Patient admitted to:","Patient admitted to:","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Pharmacology treatment","Pharmacology treatment","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Physiotherapy treatment received before admission","Physiotherapy treatment received before admission","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Pins and Needles","Pins and Needles","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Procedure performed","Procedure performed","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Review of Systems","Review of Systems","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Side of diagnosis","Side of diagnosis","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Side of pain","Side of pain","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Side of procedure","Side of procedure","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Site of diagnosis","Site of diagnosis","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Site of pain","Site of pain","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Site of procedure","Site of procedure","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Specify type of gait training","Specify type of gait training","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Status of patient in Amman RSP","Status of patient in Amman RSP","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Tingling","Tingling","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Transfer from Amman RSP","Transfer from Amman RSP","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Treatment Plan","Treatment Plan","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Type of admission","Type of admission","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Date of Injury","Date of Injury","Date","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Date of admission","Date of admission","Date","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Date of last dose","Date of last dose","Date","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Date of next DN4 assessment","Date of next DN4 assessment","Date","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Date of procedure","Date of procedure","Date","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Lower limb length","Lower limb length","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Neuropathic pain score","Neuropathic pain score","Numeric","Computed",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Number of physiotherapy sessions","Number of physiotherapy sessions","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Pain score","Pain score","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Thigh circumference","Thigh circumference","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Weight","Weight","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Abdomen examination","Abdomen examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Chest examination","Chest examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Comment of procedure","Comment of procedure","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Comments about allergy","Comments about allergy","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Comments about treatment plan","Comments about treatment plan","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Description of abnormal vital signs","Description of abnormal vital signs","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Dose and frequency","Dose and frequency","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, General examination","General examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Genitalia examination","Genitalia examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, HEENT examination","HEENT examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Heart examination","Heart examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, History of present illness (context)","History of present illness (context)","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Locomotor / extremities examination","Locomotor / extremities examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Medication prescribed to patient at arrival","Medication prescribed to patient at arrival","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Neurologic examination","Neurologic examination","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Past medical history, comments","Past medical history, comments","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Review of systems, abnormal findings","Review of systems, abnormal findings","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Sensory examination/ skin lesions, wounds","Sensory examination/ skin lesions, wounds","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Significant findings, social history","Significant findings, social history","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Site of pain, other","Site of pain, other","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Type of medication","Type of medication","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, When does the pain occur","When does the pain occur","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Other procedure performed","Other procedure performed","Text","Misc",false);
### ADDING THE CHILD CONCEPTS


call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Abnormal","Abnormal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acetabulum","Acetabulum","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Achilles tendon","Achilles tendon","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acquired clawhand, clubhand, clawfoot, and clubfoot","Acquired clawhand, clubhand, clawfoot, and clubfoot","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acquired unequal limb length","Acquired unequal limb length","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acquired wrist or foot drop","Acquired wrist or foot drop","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acromioclavicular joint","Acromioclavicular joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acute Ischaemic Heart Disease","Acute Ischaemic Heart Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acute and subacute endocarditis","Acute and subacute endocarditis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acute myocarditis","Acute myocarditis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acute osteomyelitis","Acute osteomyelitis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acute pericarditis","Acute pericarditis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Advancement of flap","Advancement of flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Analgesia","Analgesia","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Anastomosis, graft, suture of Peripheral Nerve","Anastomosis, graft, suture of Peripheral Nerve","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Anemia","Anemia","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Angina Pectoris","Angina Pectoris","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ankylosis of joint","Ankylosis of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Antibiotics","Antibiotics","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Application of an external fixation device","Application of an external fixation device","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Application of back slab","Application of back slab","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Application of cast","Application of cast","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Arterial embolism and thrombosis","Arterial embolism and thrombosis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Arteriovenous aneurysm","Arteriovenous aneurysm","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Arthrodesis","Arthrodesis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Arthrolysis","Arthrolysis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Atherosclerosis","Atherosclerosis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Axial Flap","Axial Flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Axillary","Axillary","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Back wall of thorax","Back wall of thorax","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bedridden since surgery","Bedridden since surgery","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Biopsy of bone","Biopsy of bone","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Biopsy of joint structure","Biopsy of joint structure","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bleeding or Clotting Disorders","Bleeding or Clotting Disorders","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bone debridement","Bone debridement","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bone graft","Bone graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bone graft failure","Bone graft failure","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bone graft infection","Bone graft infection","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bone lengthening","Bone lengthening","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Brachial plexus","Brachial plexus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Burn contracture of skin","Burn contracture of skin","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bursopathy","Bursopathy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Calcification and ossification of muscle","Calcification and ossification of muscle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Capsulectomy procedure","Capsulectomy procedure","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cardiac Arrest","Cardiac Arrest","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cardiac Tamponade","Cardiac Tamponade","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cardiogenic Shock","Cardiogenic Shock","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cardiomyopathy","Cardiomyopathy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cardiovascular Disease","Cardiovascular Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Carpal","Carpal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cervical spine","Cervical spine","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cervical vertebra","Cervical vertebra","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Change of dressing","Change of dressing","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Change or adjustment of external fixation device","Change or adjustment of external fixation device","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Chronic instability of knee","Chronic instability of knee","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Chronic ischaemic heart disease","Chronic ischaemic heart disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Chronic osteomyelitis","Chronic osteomyelitis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Clavicle","Clavicle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Closed biopsy of skin and subcutaneous cell tissue","Closed biopsy of skin and subcutaneous cell tissue","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Closed fracture","Closed fracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Closed reduction of fracture, with/without pin","Closed reduction of fracture, with/without pin","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Coccyx","Coccyx","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Complications of internal orthopaedic prosthetic devices, implants and grafts","Complications of internal orthopaedic prosthetic devices, implants and grafts","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Congenital Disorders","Congenital Disorders","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Congenital malformation of musculoskeletal system","Congenital malformation of musculoskeletal system","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Congenital malformation of spinal cord","Congenital malformation of spinal cord","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Contracture of joint","Contracture of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Contracture of muscle","Contracture of muscle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Contracture of tendon","Contracture of tendon","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Coronoidectomy","Coronoidectomy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Corrective osteotomy","Corrective osteotomy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Crushing injury","Crushing injury","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"DVT prophylaxis","DVT prophylaxis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Delayed suture of wound","Delayed suture of wound","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Delayed union of fracture","Delayed union of fracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Dermabrasion","Dermabrasion","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Diabetes","Diabetes","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Diseases of the Musculoskeletal System","Diseases of the Musculoskeletal System","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Dislocation, sprain and strain","Dislocation, sprain and strain","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disorder of ligament","Disorder of ligament","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disorder of muscle","Disorder of muscle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disruption of traumatic injury wound repair","Disruption of traumatic injury wound repair","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disruption of wound","Disruption of wound","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Division of flap","Division of flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Drugs","Drugs","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Dynamization of external fixator","Dynamization of external fixator","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Elongation of tendon achilles","Elongation of tendon achilles","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Epiphysiodesis","Epiphysiodesis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Excision of head of ulna","Excision of head of ulna","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Excision of peripheral neuroma","Excision of peripheral neuroma","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Excisional debridement of wound, infection, or burn","Excisional debridement of wound, infection, or burn","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Exploration of nerve","Exploration of nerve","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Facial bones","Facial bones","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Femoral","Femoral","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Femur distal","Femur distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Femur proximal","Femur proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Femur shaft","Femur shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fibula distal","Fibula distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fibula proximal","Fibula proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fibula shaft","Fibula shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Filling of segmental defect by bone transport","Filling of segmental defect by bone transport","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fingers","Fingers","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fistula of joint","Fistula of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fixation of fracture using pins","Fixation of fracture using pins","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Flail joint","Flail joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Food","Food","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Foreign body granuloma of soft tissue","Foreign body granuloma of soft tissue","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fracture of bone following insertion of orthopaedic implant, joint prosthesis, or bone plate","Fracture of bone following insertion of orthopaedic implant, joint prosthesis, or bone plate","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Front wall of thorax","Front wall of thorax","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Full thickness skin graft","Full thickness skin graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Gastrointestinal Problem","Gastrointestinal Problem","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Genitourinary Symptoms","Genitourinary Symptoms","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Grafting of cartilage","Grafting of cartilage","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Head","Head","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Heart Disease","Heart Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Heart Failure","Heart Failure","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hip joint","Hip joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"History of Cancer","History of Cancer","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Humerus distal","Humerus distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Humerus proximal","Humerus proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Humerus shaft","Humerus shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hypertension","Hypertension","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hypertensive Heart Disease","Hypertensive Heart Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hypertensive Renal Disease","Hypertensive Renal Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hypotension","Hypotension","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ilium","Ilium","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Infection and inflammatory reaction due to internal fixation device","Infection and inflammatory reaction due to internal fixation device","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Infection of amputation stump","Infection of amputation stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injection of steroid","Injection of steroid","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injuries of nerves involving multiple body regions","Injuries of nerves involving multiple body regions","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injury of blood vessel(s)","Injury of blood vessel(s)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injury of muscle and tendons","Injury of muscle and tendons","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injury of nerve(s)","Injury of nerve(s)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of","Insertion of","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of Central Line","Insertion of Central Line","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of PICC line","Insertion of PICC line","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of drain or tube","Insertion of drain or tube","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Instability of joint","Instability of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Integra skin graft","Integra skin graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Internal fixation using intramedullary nail","Internal fixation using intramedullary nail","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Internal fixation using plate","Internal fixation using plate","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Internal fixation using screw","Internal fixation using screw","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Internal fixation using wire","Internal fixation using wire","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Joint capsulodesis","Joint capsulodesis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Joint derangement","Joint derangement","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Joint disorder","Joint disorder","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Kidney Disease","Kidney Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Larynx","Larynx","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Late Effect of Tendon Injury","Late Effect of Tendon Injury","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lateral plantar","Lateral plantar","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ligament reconstruction","Ligament reconstruction","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Liver Disease","Liver Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Local rotation flap","Local rotation flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Local subcutaneous pedicled V-Y flap","Local subcutaneous pedicled V-Y flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lower jaw","Lower jaw","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lower limb","Lower limb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lower limb peripheral nerves","Lower limb peripheral nerves","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lumbar vertebra","Lumbar vertebra","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lysis of adhesions of tendon / tenolysis","Lysis of adhesions of tendon / tenolysis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Malunion of fracture","Malunion of fracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Manipulation under anesthesia","Manipulation under anesthesia","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Medial plantar","Medial plantar","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Median","Median","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Mental Health Support","Mental Health Support","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Metacarpal","Metacarpal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Metatarsal","Metatarsal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Multiple crushing injuries","Multiple crushing injuries","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Multiple dislocations, sprains and strains","Multiple dislocations, sprains and strains","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Multiple fractures","Multiple fractures","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Myocardial infarction","Myocardial infarction","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Necrosis of amputation stump","Necrosis of amputation stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nerve block","Nerve block","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nerve graft","Nerve graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Neurological Disorder","Neurological Disorder","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Neuroma of amputation stump","Neuroma of amputation stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Neurorrhaphy / suture of nerve","Neurorrhaphy / suture of nerve","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"New admission","New admission","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nonunion of fracture","Nonunion of fracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Normal","Normal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open biopsy of soft tissue","Open biopsy of soft tissue","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open fracture","Open fracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open reduction of fracture alone","Open reduction of fracture alone","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open reduction of fracture with K-wire","Open reduction of fracture with K-wire","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open reduction of fracture with nail/plate","Open reduction of fracture with nail/plate","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open wound of lower limb","Open wound of lower limb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Open wound of upper limb","Open wound of upper limb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Osteonecrosis due to previous trauma","Osteonecrosis due to previous trauma","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Osteophyte","Osteophyte","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Osteotomy","Osteotomy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other Endocrine Disorders","Other Endocrine Disorders","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other Hematologic Diseases","Other Hematologic Diseases","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other Pathologies","Other Pathologies","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other acquired deformities of limb","Other acquired deformities of limb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other complications of amputation stump","Other complications of amputation stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other disorders of bone","Other disorders of bone","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Partial thickness skin graft","Partial thickness skin graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Patella","Patella","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pelvis","Pelvis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Peripheral nerve or ganglion decompression or lysis of adhesions","Peripheral nerve or ganglion decompression or lysis of adhesions","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Peripheral vascular disease","Peripheral vascular disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Peripheral vascular shunt or bypass","Peripheral vascular shunt or bypass","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Peroneal","Peroneal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pharmacology","Pharmacology","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Phlebitis and Thrombophlebitis","Phlebitis and Thrombophlebitis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Physiotherapy","Physiotherapy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Plaster of Paris","Plaster of Paris","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Plastic repair by z plasty","Plastic repair by z plasty","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pollicisation of finger or thumb","Pollicisation of finger or thumb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Post-operative follow-up","Post-operative follow-up","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Post-traumatic wound infection","Post-traumatic wound infection","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Posteromedial release of clubfoot","Posteromedial release of clubfoot","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Postprocedural disorders of circulatory system","Postprocedural disorders of circulatory system","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pre-operative","Pre-operative","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pubis","Pubis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pulmonary Embolism","Pulmonary Embolism","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pulmonary valve disorders","Pulmonary valve disorders","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Quadricepsplasty","Quadricepsplasty","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Radial","Radial","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Radial head","Radial head","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Radius distal","Radius distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Radius proximal","Radius proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Radius shaft","Radius shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Reamputation of stump","Reamputation of stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Recurrent dislocation of joint","Recurrent dislocation of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Regional flap","Regional flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Release [excision] scar contracture","Release [excision] scar contracture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of K-wire","Removal of K-wire","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of an external fixation device","Removal of an external fixation device","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of drain or tube","Removal of drain or tube","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of external fixator pin","Removal of external fixator pin","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of foreign body or device from skin and subcutaneous cell tissue","Removal of foreign body or device from skin and subcutaneous cell tissue","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of nail","Removal of nail","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of plate from bone","Removal of plate from bone","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of screws from bone","Removal of screws from bone","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of sutures","Removal of sutures","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Repair of tendon","Repair of tendon","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Replacement of","Replacement of","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Respiratory Disease","Respiratory Disease","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Revision of amputation stump","Revision of amputation stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Revision of scar","Revision of scar","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ribs","Ribs","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sacrum","Sacrum","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Scapula","Scapula","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sciatic","Sciatic","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Secondary Hypertension","Secondary Hypertension","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Secondary closure of stump","Secondary closure of stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sequestrectomy","Sequestrectomy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Shoulder joint","Shoulder joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Skeletal traction","Skeletal traction","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Skin flap operation","Skin flap operation","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Skin graft operation","Skin graft operation","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Skull","Skull","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Soft tissue disorder related to use, overuse, and pressure","Soft tissue disorder related to use, overuse, and pressure","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Spontaneous rupture of extensor tendons","Spontaneous rupture of extensor tendons","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Spontaneous rupture of flexor tendons","Spontaneous rupture of flexor tendons","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Spontaneous rupture of other tendons","Spontaneous rupture of other tendons","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Stable","Stable","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sternoclavicular joint","Sternoclavicular joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sternum","Sternum","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Stiffness of joint","Stiffness of joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Stroke","Stroke","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Superficial injury","Superficial injury","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tarsal","Tarsal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tendon graft","Tendon graft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tendon release","Tendon release","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tendon transfer or transplantation","Tendon transfer or transplantation","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tenorrhaphy / suture of tendon","Tenorrhaphy / suture of tendon","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Thinning of skin flap","Thinning of skin flap","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Thoracic spine","Thoracic spine","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Thoracic vertebra","Thoracic vertebra","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Throat","Throat","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Thumb","Thumb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tibia distal","Tibia distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tibia proximal","Tibia proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tibia shaft","Tibia shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tibial","Tibial","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Trachea","Trachea","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tracheostomy","Tracheostomy","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Transfer from IPD","Transfer from IPD","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Transfer from OPD","Transfer from OPD","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputatin at level between knee and ankle","Traumatic amputatin at level between knee and ankle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputatin at other parts of foot","Traumatic amputatin at other parts of foot","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation at elbow level","Traumatic amputation at elbow level","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation at hip joint","Traumatic amputation at hip joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation at level between elbow and wrist","Traumatic amputation at level between elbow and wrist","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation at level between shoulder and elbow","Traumatic amputation at level between shoulder and elbow","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation at shoulder joint","Traumatic amputation at shoulder joint","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation between hip and knee","Traumatic amputation between hip and knee","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation involving multiple body region","Traumatic amputation involving multiple body region","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation of foot at ankle level","Traumatic amputation of foot at ankle level","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation of hand at wrist level","Traumatic amputation of hand at wrist level","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic amputation of two or more fingers alone (complete) (partial)","Traumatic amputation of two or more fingers alone (complete) (partial)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic compartment syndrome","Traumatic compartment syndrome","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Traumatic ischaemia of muscle","Traumatic ischaemia of muscle","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Trimming of stump","Trimming of stump","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Type 1 diabetes mellitus","Type 1 diabetes mellitus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Type 2 diabetes mellitus","Type 2 diabetes mellitus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ulna distal","Ulna distal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ulna proximal","Ulna proximal","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ulna shaft","Ulna shaft","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ulnar","Ulnar","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper & Lower","Upper & Lower","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper arm","Upper arm","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper jaw","Upper jaw","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper limb","Upper limb","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper limb peripheral nerves","Upper limb peripheral nerves","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Valgus deformity","Valgus deformity","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Varus deformity","Varus deformity","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Vitamins","Vitamins","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Walking Cane","Walking Cane","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Wound drainage","Wound drainage","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Itching","Itching","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Numbness","Numbness","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pins and needles","Pins and needles","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tingling","Tingling","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of (cement) spacer","Insertion of (cement) spacer",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Plaster of Paris (POP)","Plaster of Paris (POP)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Removal of sutures (clips etc.), skin","Removal of sutures (clips etc.), skin",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Replacement of (cement) spacer","Replacement of (cement) spacer",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Elongation of tendon achilles (ETA)","Elongation of tendon achilles (ETA)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of PICC line (peripherally inserted central catheter)","Insertion of PICC line (peripherally inserted central catheter)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Thigh circumference Left","Thigh circumference Left","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Thigh circumference Right","Thigh circumference Right","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Lower limb length Left","Lower limb length Left","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"IME, Lower limb length Right","Lower limb length Right","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pyogenic (septic) arthritis","Pyogenic (septic) arthritis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Flexion deformity (or contracture)","Flexion deformity (or contracture)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acquired flat foot (pes planus)","Acquired flat foot (pes planus)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Short Achilles tendon (acquired)","Short Achilles tendon (acquired)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disorder of continuity of bone (bone gap)","Disorder of continuity of bone (bone gap)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Insertion of  drain or tube","Insertion of  drain or tube","N/A","Misc",false);


#### Adding Numeric concepts to the concept Numeric table

INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Number of physiotherapy sessions" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en' and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Pain score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,10,NULL,NULL,0,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Neuropathic pain score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en' and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Weight" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"kg",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Thigh circumference" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en' and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Lower limb length" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en' and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Thigh circumference Right" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"cm",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Thigh circumference Left" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"cm",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Lower limb length Right" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"cm",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "IME, Lower limb length Left" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"cm",1,1);

#### Adding Description of the  concepts to the concept description table

INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Significant findings, social history" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"Record significant findings related to smoking, alcohol use, etc. affecting patient treatment",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Review of systems, abnormal findings" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"Record any abnormal findings when doing the review of systems",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Pain score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"For children 3-5 years, use Wong-Baker scale.  For children over 5 years and adults use visual numeric pain scale",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Neuropathic pain score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"If the score is equal or greater than 4/10, the test is positive",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Sensory examination/ skin lesions, wounds" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"To record important remarks recording skin lesions, wound localization, and description",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description(concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid)
VALUES ((select concept_id from concept_name where name = "IME, Medication prescribed to patient at arrival" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"Note of any medication prescribed to the patient at first consultation",'en',1,now(),NULL,NULL,uuid());

################### Recheck #################################################################