set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Type of physiotherapy prescription","Type of physiotherapy prescription",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Passive mobilization, joint","Passive mobilization, joint",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Passive mobilization, degree or level","Passive mobilization, degree or level",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Assisted / Active mobilization, joint","Assisted / Active mobilization, joint",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Assisted / Active mobilization, degree or level","Assisted / Active mobilization, degree or level",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, exercise type","Muscle strengthening, exercise type",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, isometric","Muscle strengthening, isometric",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, PRE","Muscle strengthening, PRE",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, isotonic","Muscle strengthening, isotonic",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle stretching","Muscle stretching",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Gait training","Gait training",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Type of gait training","Type of gait training",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Wheelchair mobility training","Wheelchair mobility training",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Positioning","Positioning",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Balance and proprioceptive exercises","Balance and proprioceptive exercises",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Physiotherapy measure for neuropathic pain","Physiotherapy measure for neuropathic pain",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Date of physiotherapy prescription","Date of physiotherapy prescription",'Date','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Physiotherapy objective","Physiotherapy objective",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Treatment duration","Treatment duration",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Passive mobilization, other joint","Passive mobilization, other joint",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Passive mobilization, other degree or level","Passive mobilization, other degree or level",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Assisted / Active mobilization, other joint","Assisted / Active mobilization, other joint",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Assisted / Active mobilization, other degree or level","Assisted / Active mobilization, other degree or level",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, other exercise","Muscle strengthening, other exercise",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle strengthening, other muscle","Muscle strengthening, other muscle",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Muscle stretching, other","Muscle stretching, other",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Partial weight bearing, degree and level","Partial weight bearing, degree and level",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Functional activities / ADL training","Functional activities / ADL training",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Positioning, other","Positioning, other",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Orthosis / Splint / Prosthesis","Orthosis / Splint / Prosthesis",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Chest physiotherapy","Chest physiotherapy",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PP, Other interventions","Other interventions",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Initial physiotherapy prescription","Initial physiotherapy prescription",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Follow-up physiotherapy prescription","Follow-up physiotherapy prescription",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right hip","Right hip",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left hip","Left hip",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both hips","Both hips",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right knee","Right knee",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left knee","Left knee",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both knees","Both knees",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right ankle","Right ankle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left ankle","Left ankle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both ankles","Both ankles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right subtalar joint","Right subtalar joint",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left subtalar joint","Left subtalar joint",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both subtalar joints","Both subtalar joints",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right shoulder","Right shoulder",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left shoulder","Left shoulder",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both shoulders","Both shoulders",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right elbow","Right elbow",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left elbow","Left elbow",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both elbows","Both elbows",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right radioulnar joint","Right radioulnar joint",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left radioulnar joint","Left radioulnar joint",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both radioulnar joints","Both radioulnar joints",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right wrist","Right wrist",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left wrist","Left wrist",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both wrists","Both wrists",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Isometric","Isometric",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Progressive resistive exercise (PRE)","Progressive resistive exercise (PRE)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Isotonic","Isotonic",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right hip girdle muscles","Right hip girdle muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left hip girdle muscles","Left hip girdle muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both hip girdle muscles","Both hip girdle muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right quadriceps","Right quadriceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left quadriceps","Left quadriceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both quadriceps","Both quadriceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right hamstring","Right hamstring",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left hamstring","Left hamstring",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both hamstrings","Both hamstrings",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right tibialis anterior","Right tibialis anterior",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left tibialis anterior","Left tibialis anterior",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both tibialis anterior","Both tibialis anterior",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right calf muscles","Right calf muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left calf muscles","Left calf muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both calf muscles","Both calf muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right peronei","Right peronei",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left peronei","Left peronei",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both peronei","Both peronei",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right shoulder girdle","Right shoulder girdle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left shoulder girdle","Left shoulder girdle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both shoulder girdles","Both shoulder girdles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right triceps","Right triceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left triceps","Left triceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both triceps","Both triceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right biceps","Right biceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left biceps","Left biceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both biceps","Both biceps",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right supinator","Right supinator",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left supinator","Left supinator",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both supinators","Both supinators",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right pronator","Right pronator",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left pronator","Left pronator",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both pronators","Both pronators",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right wrist flexor","Right wrist flexor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left wrist flexor","Left wrist flexor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both wrist flexors","Both wrist flexors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right wrist extensor","Right wrist extensor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left wrist extensor","Left wrist extensor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both wrist extensors","Both wrist extensors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right ulnar deviation","Right ulnar deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left ulnar deviation","Left ulnar deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both ulnar deviation","Both ulnar deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right radial deviation","Right radial deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left radial deviation","Left radial deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both radial deviation","Both radial deviation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Iliopsoas","Right Iliopsoas",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Iliopsoas","Left Iliopsoas",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Iliopsoas","Both Iliopsoas",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Gluteus Maximus","Right Gluteus Maximus",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Gluteus maximus","Left Gluteus maximus",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Glutei","Both Glutei",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Hip abductors","Right Hip abductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Hip abductors","Left Hip abductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both hip abductors","Both hip abductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Hip Adductors","Right Hip Adductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Hip adductors","Left Hip adductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both hip adductors","Both hip adductors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Deltoid muscle","Right Deltoid muscle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Deltoid mucle","Left Deltoid mucle",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Pectoralis Major","Right Pectoralis Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Pectoralis Major","Left Pectoralis Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Pectoralis Major","Both Pectoralis Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Teres Major","Right Teres Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Teres Major","Left Teres Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Teres Major","Both Teres Major",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Teres Minor","Right Teres Minor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Teres Minor","Left Teres Minor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Teres Minor","Both Teres Minor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Deltoid Muscles","Deltoid Muscles",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Pectoralis minor","Right Pectoralis minor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Pectoralis minor","Left Pectoralis minor",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Pectoralis minors","Both Pectoralis minors",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right Supraspinatus","Right Supraspinatus",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Left Supraspinatus","Left Supraspinatus",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both Supraspinatus","Both Supraspinatus",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No weight bearing","No weight bearing",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Toe touch","Toe touch",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Partial weight bearing (PWB)","Partial weight bearing (PWB)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Full weight bearing (FWB)","Full weight bearing (FWB)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Propping heel free","Propping heel free",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Prone position","Prone position",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sound leg","Sound leg",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Injured leg","Injured leg",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Both legs","Both legs",'N/A','Misc',false);
