- name: Find existing event omod
  find:
    paths: /opt/openmrs/modules
    patterns: event*.omod
  register: result

- name: Delete event omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get event_omod omod from s3 bucket and place it in /opt/openmrs/modules
  get_url:
    url: "{{ event_omod }}"
    dest: /opt/openmrs/modules/
    mode: 0644
    owner: bahmni
    group: bahmni
