set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;


-- Parent concepts
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Date recorded","Date recorded",'Date','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Type of assessment","Type of assessment",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Previous history of physiotherapy","Previous history of physiotherapy",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Details of previous physiotherapy","Details of previous physiotherapy",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Affected side","Affected side",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Does the patient use an assistive device or orthosis?","Does the patient use an assistive device or orthosis?",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Type of assistive device or orthosis","Type of assistive device or orthosis",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Other type of assistive device","Other type of assistive device",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Comments about assistive device or orthosis","Comments about assistive device or orthosis",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Pain Score","Pain Score",'Numeric','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Side of pain","Side of pain",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Site of pain","Site of pain",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Site of pain, other","Site of pain, other",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Type of pain","Type of pain",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, When does the pain occur","When does the pain occur",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Summary neurological examination (sensation)","Summary neurological examination (sensation)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Summary neurological examination (sensation), comments","Summary neurological examination (sensation), comments",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Affected region","Affected region",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Leg Length Discrepancy (LLD)","Leg Length Discrepancy (LLD)",'Numeric','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Comments about LLD","Comments about LLD",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip flexion","Left : Hip flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip flexion","Right : Hip flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip extension","Left : Hip extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip extension","Right : Hip extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip abduction","Left : Hip abduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip abduction","Right : Hip abduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip adduction","Left : Hip adduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip adduction","Right : Hip adduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip int. rotation","Left : Hip int. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip int. rotation","Right : Hip int. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip ext. rotation","Left : Hip ext. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip ext. rotation","Right : Hip ext. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Knee flexion","Left : Knee flexion.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Knee flexion","Right : Knee flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Knee extension","Left : Knee extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Knee extension","Right : Knee extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle dorsiflex.","Left : Ankle dorsiflex.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle dorsiflex.","Right : Ankle dorsiflex.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle planterflex","Left : Ankle planterflex",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle planterflex","Right : Ankle planterflex",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle inversion","Left : Ankle inversion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle inversion","Right : Ankle inversion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle eversion","Left : Ankle eversion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle eversion","Right : Ankle eversion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Big toe flexion","Left : Big toe flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Big toe extension","Right : Big toe extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip flexors","Left : Hip flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip flexors","Right : Hip flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip extensors","Left : Hip extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip extensors","Right : Hip extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip abductors","Left : Hip abductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip abductors","Right : Hip abductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip adductors","Left : Hip adductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip adductors","Right : Hip adductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip int. rotators","Left : Hip int. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip int. rotators","Right : Hip int. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Hip ext. rotators","Left : Hip ext. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Hip ext. rotators","Right : Hip ext. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Knee flexors","Left : Knee flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Knee flexors","Right : Knee flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Knee extensors","Left : Knee extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Knee extensors","Right : Knee extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle dorsiflexors","Left : Ankle dorsiflexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle dorsiflexors","Right : Ankle dorsiflexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle planterflexors","Left : Ankle planterflexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle planterflexors","Right : Ankle planterflexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle invertors","Left : Ankle invertors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle invertors","Right : Ankle invertors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ankle evertors","Left : Ankle evertors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ankle evertors","Right : Ankle evertors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Big toe flexors","Left : Big toe flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Big toe extensors","Right : Big toe extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Sitting Balance","Sitting Balance",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Rises from chair","Rises from chair",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Attempts to rise","Attempts to rise",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Immediate standing, balance (first 5 seconds)","Immediate standing, balance (first 5 seconds)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Standing balance","Standing balance",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Nudged","Nudged",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Eyes closed","Eyes closed",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Turning 360 degrees, 1","Turning 360 degrees, 1",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Turning 360 degrees, 2","Turning 360 degrees, 2",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Sitting down","Sitting down",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Balance Score","Balance Score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Indication of gait","Indication of gait",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Step length and height","Step length and height",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Foot clearance","Foot clearance",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Step symmetry","Step symmetry",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Step continuity","Step continuity",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Path","Path",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Trunk","Trunk",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Walking time","Walking time",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Gait Score","Gait Score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Total Score Tinetti Balance Assessment Tool","Total Score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Risk of falls","Risk of falls",'Text','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, How old is the patient","How old is the patient",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Any of your usual work, housework or school activities upper","Any of your usual work, housework or school activities",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Your usual hobbies, recreational or sporting activities","Your usual hobbies, recreational or sporting activities",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Getting into or out of the bath (into the bathtub)","Getting into or out of the bath (into the bathtub)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Walking between rooms","Walking between rooms",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Putting on your shoes and socks","Putting on your shoes and socks",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Squatting (Standing - sitting)","Squatting (Standing - sitting)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Lifting an object (like a bag of groceries) from the floor","Lifting an object (like a bag of groceries) from the floor",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Performing light activities around your home (changing bulbs, decorating, cleaning)","Performing light activities around your home (changing bulbs, decorating, cleaning)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Performing heavy activities around your home (gardening, maintenance etc.)","Performing heavy activities around your home (gardening, maintenance etc.)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Getting into or out of a car","Getting into or out of a car",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Walking two blocks (~160m)","Walking two blocks (~160m)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Walking a mile (~ 1.6 km)","Walking a mile (~ 1.6 km)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Going up or down 10 stairs (about one flight of stairs)","Going up or down 10 stairs (about one flight of stairs)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Standing for one hour (e.g. waiting in a line)","Standing for one hour (e.g. waiting in a line)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Sitting for one hour (e.g. wedding)","Sitting for one hour (e.g. wedding)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Running on even ground","Running on even ground",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Running on uneven ground","Running on uneven ground",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Making sharp turns while running fast","Making sharp turns while running fast",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Hopping","Hopping",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Rolling over in bed","Rolling over in bed",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Total Score Lower Extremity Functional Index (LEFI)","Total Score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get down on my knees without holding on to something","I could get down on my knees without holding on to something",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could keep up when I played with other kids","I could keep up when I played with other kids",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk for 15 minutes","I could walk for 15 minutes",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk between rooms","I could walk between rooms",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get on and off the toilet without using my arms","I could get on and off the toilet without using my arms",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get on and off a low chair","I could get on and off a low chair",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get up from the floor by myself","I could get up from the floor by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could sit on a bench without support for 15 minutes?","I could sit on a bench without support for 15 minutes?",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could stand on my tiptoes to reach for something","I could stand on my tiptoes to reach for something",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could stand on my tiptoes to put something (e.g. a pack of sugar) on a shelf","I could stand on my tiptoes to put something (e.g. a pack of sugar) on a shelf",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk on slightly uneven surfaces (such as cracked pavement)","I could walk on slightly uneven surfaces (such as cracked pavement)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk on rough, uneven surfaces (such as lawns/ fields)","I could walk on rough, uneven surfaces (such as lawns/ fields)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk up and down ramps and hills","I could walk up and down ramps and hills",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk up and down curbs (steps)","I could walk up and down curbs (steps)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get in and out of a bus","I could get in and out of a bus",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could get in and out of a car","I could get in and out of a car",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk across the room","I could walk across the room",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could walk while wearing a backpack full of books","I could walk while wearing a backpack full of books",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could bend over to pick something up","I could bend over to pick something up",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I could exercise that others my age can do","I could exercise that others my age can do",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Total Score Pediatric Lower Extremity Function - Mobility","Total Score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder flexion","Left : Shoulder flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder flexion","Right : Shoulder flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder extension","Left : Shoulder extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder extension","Right : Shoulder extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder abduction","Left : Shoulder abduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder abduction","Right : Shoulder abduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder adduction","Left : Shoulder adduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder adduction","Right : Shoulder adduction",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder int. rotation","Left : Shoulder int. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder int. rotation","Right : Shoulder int. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder ext. rotation","Left : Shoulder ext. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder ext. rotation","Right : Shoulder ext. rotation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Elbow flexion","Left : Elbow flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Elbow flexion","Right : Elbow flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Elbow extension","Left : Elbow extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Elbow extension","Right : Elbow extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Forearm pronation","Left : Forearm pronation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Forearm pronation","Right : Forearm pronation",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Forearm supination","Left : Forearm supination",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Forearm supination","Right : Forearm supination",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Wrist flexion","Left : Wrist flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Wrist flexion","Right : Wrist flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Wrist extension","Left : Wrist extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Wrist extension","Right : Wrist extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Ulnar Dev.","Left : Ulnar Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Ulnar Dev.","Right : Ulnar Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Radial Dev.","Left : Radial Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Radial Dev.","Right : Radial Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Fingers flexion","Right : Fingers flexion",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Fingers extension","Left : Fingers extension",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Does the patient have a hand or finger injury","Does the patient have a hand or finger injury",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Distance tip (2nd -5th)","Distance tip (2nd -5th)",'Numeric','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Distance tip (Thumb - 2nd)","Distance tip (Thumb - 2nd)",'Numeric','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Side of assessment","Side of assessment",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : Thumb MC","Flex : Thumb MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : Thumb MC","Ext. : Thumb MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : Thumb DIP","Flex : Thumb DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : Thumb DIP","Ext. : Thumb DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 2nd Finger MC","Flex : 2nd Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 2nd Finger MC","Ext. : 2nd Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 3rd Finger MC","Flex : 3rd Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 3rd Finger MC","Ext. : 3rd Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 4th Finger MC","Flex : 4th Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 4th Finger MC","Ext. : 4th Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 5th Finger MC","Flex : 5th Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 5th Finger MC","Ext. : 5th Finger MC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 2nd Finger PIP","Flex : 2nd Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 2nd Finger PIP","Ext : 2nd Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 3rd Finger PIP","Flex : 3rd Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 3rd Finger PIP","Ext : 3rd Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 4th Finger PIP","Flex : 4th Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 4th Finger PIP","Ext : 4th Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 5th Finger PIP","Flex : 5th Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 5th Finger PIP","Ext : 5th Finger PIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 2nd Finger DIP","Flex : 2nd Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 2nd Finger DIP","Ext. : 2nd Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 3rd Finger DIP","Flex : 3rd Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 3rd Finger DIP","Ext. : 3rd Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 4th Finger DIP","Flex : 4th Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 4th Finger DIP","Ext. : 4th Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Flex : 5th Finger DIP","Flex : 5th Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Ext : 5th Finger DIP","Ext. : 5th Finger DIP",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder flexors","Left : Shoulder flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder flexors","Right : Shoulder flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder extensors","Left : Shoulder extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder extensors","Right : Shoulder extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder abductors","Left : Shoulder abductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder abductors","Right : Shoulder abductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder adductors","Left : Shoulder adductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder adductors","Right : Shoulder adductors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder int. rotators","Left : Shoulder int. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder int. rotators","Right : Shoulder int. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Shoulder ext. rotators","Left : Shoulder ext. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Shoulder ext. rotators","Right : Shoulder ext. rotators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Elbow flexors","Left : Elbow flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Elbow flexors","Right : Elbow flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Elbow extensors","Left : Elbow extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Elbow extensors","Right : Elbow extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Forearm pronators","Left : Forearm pronators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Forearm pronators","Right : Forearm pronators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Forearm supinators","Left : Forearm supinators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Forearm supinators","Right : Forearm supinators",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Wrist flexors","Left : Wrist flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Wrist flexors","Right : Wrist flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Wrist extensors","Left : Wrist extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Wrist extensors","Right : Wrist extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA,MTUL Left : Ulnar Dev.","Left : Ulnar Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA,MTUL Right : Ulnar Dev.","Right : Ulnar Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA,MTUL Left : Radial Dev.","Left : Radial Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA,MTUL Right : Radial Dev.","Right : Radial Dev.",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Fingers flexors","Left : Fingers flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Fingers flexors","Right : Fingers flexors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Fingers extensors","Left : Fingers extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Fingers extensors","Right : Fingers extensors",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Chuck or three-fingered pinch","Chuck or three-fingered pinch",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Cylindrical grasp","Cylindrical grasp",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Spherical","Spherical",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Hook","Hook",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Tip pinch (or tip to tip prehension)","Tip pinch (or tip to tip prehension)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Lateral or key pinch","Lateral or key pinch",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Basic grip test, total score","Basic grip test, total score",'Numeric','Computed',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, How old is the patient","How old is the patient",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Any of your usual work, housework or school activities lower","Any of your usual work, housework or school activities",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Lifting a bag of groceries to waist level.","Lifting a bag of groceries to waist level.",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Placing an object onto or remove it from, an overhead shelf","Placing an object onto or remove it from, an overhead shelf",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Washing your hair or scalp","Washing your hair or scalp",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Pushing up on your hands (e.g. from bathtub or chair)","Pushing up on your hands (e.g. from bathtub or chair)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Preparing food (e.g. peeling, cutting)","Preparing food (e.g. peeling, cutting)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Driving","Driving",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Vacuuming, sweeping or raking","Vacuuming, sweeping or raking",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Doing up buttons (Note: Response numbering is correct!)","Doing up buttons (Note: Response numbering is correct!)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Using tools or appliances","Using tools or appliances",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Opening doors","Opening doors",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Cleaning (any type)","Cleaning (any type)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Laundering clothes (e.g. washing, ironing, folding)","Laundering clothes (e.g. washing, ironing, folding)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Opening a jar","Opening a jar",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Carrying a small suitcase with your affected limb","Carrying a small suitcase with your affected limb",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Total raw score","Total raw score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Final score","Final score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to use my fingers to point to something","I was able to use my fingers to point to something",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to take off my socks","I was able to take off my socks",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to put on and fasten my pants by myself","I was able to put on and fasten my pants by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to button and unbutton my shirt","I was able to button and unbutton my shirt",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to use a spoon to bring food up to my mouth","I was able to use a spoon to bring food up to my mouth",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to wipe myself thoroughly after using the toilet","I was able to wipe myself thoroughly after using the toilet",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to pull my pants back after using the toilet","I was able to pull my pants back after using the toilet",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to hold a plate full of food","I was able to hold a plate full of food",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to cut a piece of paper in half with scissors","I was able to cut a piece of paper in half with scissors",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to take a shower by myself (water coming from above, standing)","I was able to take a shower by myself (water coming from above, standing)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to take a bath by myself (in the bathtub)","I was able to take a bath by myself (in the bathtub)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to make a phone call with a smart phone","I was able to make a phone call with a smart phone",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to get out of bed by myself","I was able to get out of bed by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to put on my shoes by myself","I was able to put on my shoes by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to open a jar by myself","I was able to open a jar by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to put toothpaste on my toothbrush by myself (able to squeeze a tube)","I was able to put toothpaste on my toothbrush by myself (able to squeeze a tube)",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to brush my teeth by myself","I was able to brush my teeth by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to dry my back with a towel","I was able to dry my back with a towel",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to put on my clothes by myself","I was able to put on my clothes by myself",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, I was able to zip up my clothes","I was able to zip up my clothes",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Total score Pediatric Upper Extremity Function - Fine Motor, ADL","Total score",'Numeric','Computed',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Problem List","Problem List",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Treatment goals","Treatment goals",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Treatment plan and exercises","Treatment plan and exercises",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Frequency of treatment (sessions / week)","Frequency of treatment (sessions / week)",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Estimated duration per session","Estimated duration per session",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Gait and functional status of patient","Gait and functional status of patient",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Additional comments","Additional comments",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Physiotherapy treatment provided to patient in BMRC","Physiotherapy treatment provided to patient in BMRC",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Reason for discharge from physiotherapy","Reason for discharge from physiotherapy",'Coded','Question',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Home exercises / Family training","Home exercises / Family training",'Text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Points to consider / special concerns","Points to consider / special concerns",'Text','Misc',false);


-- Child concepts
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"0","0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"1","1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"2","2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"< 18 years","< 18 years",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"18+ years","18+ years",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"3 = A little bit of difficulty","3 = A little bit of difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Able to rise, 1 attempt = 2","Able to rise, 1 attempt = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Able without use of arms =2","Able without use of arms =2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Able, requires >1 attempt = 1","Able, requires >1 attempt = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Able, uses arms to help = 1","Able, uses arms to help = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Any hesitancy or multiple attempts = 0","Any hesitancy or multiple attempts = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"automatic calculation adding the score of above","automatic calculation adding the score of above",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Begins to fall = 0","Begins to fall = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Cane","Cane",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"DAMA","DAMA",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Defaulted","Defaulted",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Discharge assessment","Discharge assessment",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Discontinuous steps = 0","Discontinuous steps = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Continuous = 1","Continuous = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"0 = Extreme Difficulty or unable to perform activity","0 = Extreme Difficulty or unable to perform activity",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"0 = Extremely difficult or unable to do","0 = Extremely difficult or unable to do",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"1 = With moderate difficulty","1 = With moderate difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"2 = With a little difficulty","2 = With a little difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"3 = No difficulty","3 = No difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Follow-up assessment, communication","Follow-up assessment, communication",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Foot drop = 0","Foot drop = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"For security reasons or transportation constraints","For security reasons or transportation constraints",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Full recovery and goals met","Full recovery and goals met",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Heels almost touching while walking = 1","Heels almost touching while walking = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Heels apart = 0","Heels apart = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hyper-sensation","Hyper-sensation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Hypo-sensation","Hypo-sensation",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"L foot clears floor = 1","L foot clears floor = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Leans or slides in chair = 0","Leans or slides in chair = 0",'N/A','Misc',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lower jaw","Lower jaw",'N/A','Misc',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Lower limb","Lower limb",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Marked deviation = 0","Marked deviation = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Marked sway or uses w. aid = 0","Marked sway or uses w. aid = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Mild/moderate deviation or uses w. aid = 1","Mild/moderate deviation or uses w. aid = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"2= Moderate difficulty","2= Moderate difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Narrow stance without support = 2","Narrow stance without support = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"4 = No difficulty","4 = No difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No hesitancy = 1","No hesitancy = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No improvement since last assessment","No improvement since last assessment",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No sway but flex. Knees or back or uses arms for stability = 1","No sway but flex. Knees or back or uses arms for stability = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No sway, flex., use of arms or w. aid = 2","No sway, flex., use of arms or w. aid = 2",'N/A','Misc',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Normal","Normal",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"0 = Not able to do","0 = Not able to do",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"One axillary crutch","One axillary crutch",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"One elbow crutch","One elbow crutch",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Orthosis","Orthosis",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"1 = Quite a bit of difficulty","1 = Quite a bit of difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"R foot clears floor = 1","R foot clears floor = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right and left step length appear equal = 1","Right and left step length appear equal = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Right and left step length not equal = 0","Right and left step length not equal = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Safe, smooth motion = 2","Safe, smooth motion = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staggers, grabs, catches self = 1","Staggers, grabs, catches self = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady = 1","Steady = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady = 2","Steady = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady but uses walker or other support = 1","Steady but uses walker or other support = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady but wide stance and uses support = 1","Steady but wide stance and uses support = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady without walker or other support = 2","Steady without walker or other support = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steady, safe = 1","Steady, safe = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steps appear continuous = 1","Steps appear continuous = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steps through L = 1","Steps through L = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steps through R = 1","Steps through R = 1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Steps to = 0","Steps to = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Stopping or discontinuity between steps = 0","Stopping or discontinuity between steps = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Straight without w. aid = 2","Straight without w. aid = 2",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Transferred to external facility","Transferred to external facility",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Two axillary crutches","Two axillary crutches",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Two elbow crutches","Two elbow crutches",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Unable to without help = 0","Unable to without help = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Unsafe (misjudged distance, falls into chair) = 0","Unsafe (misjudged distance, falls into chair) = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Unsteady = 0","Unsteady = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Unsteady (grabs, staggers) = 0","Unsteady (grabs, staggers) = 0",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Unsteady (staggers, moves feet, trunk sway) = 0","Unsteady (staggers, moves feet, trunk sway) = 0",'N/A','Misc',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper jaw","Upper jaw",'N/A','Misc',false);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Upper limb","Upper limb",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Uses arms or not a smooth motion =1","Uses arms or not a smooth motion =1",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"3 = With a little difficulty","3 = With a little difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"3 = With a little trouble","3 = With a little trouble",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"1 = With a lot of trouble","1 = With a lot of trouble",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"2 = With moderate difficulty","2 = With moderate difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"1 = With much difficulty","1 = With much difficulty",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"4 = With no trouble","4 = With no trouble",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"2 = With some trouble","2 = With some trouble",'N/A','Misc',false);

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Big toe flexion","Right : Big toe flexion","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Big toe extension","Left : Big toe extension","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Big toe flexors","Right : Big toe flexors","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Big toe extensors","Left : Big toe extensors","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Left : Fingers flexion","Left : Fingers flexion","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PA, Right : Fingers extension","Right : Fingers extension","Text","Misc",false);

-- Adding Numeric Concepts
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Pain Score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Leg Length Discrepancy (LLD)" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Balance Score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Gait Score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Total Score Tinetti Balance Assessment Tool" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Total Score Lower Extremity Functional Index (LEFI)" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Total Score Pediatric Lower Extremity Function - Mobility" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Distance tip (2nd -5th)" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Distance tip (Thumb - 2nd)" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Basic grip test, total score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Total raw score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Final score" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision) VALUES ((select concept_id from concept_name where name = "PA, Total score Pediatric Upper Extremity Function - Fine Motor, ADL" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en'  and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);


-- Adding Help text to Concepts
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Pain Score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'For children 3-5 years, use Wong-Baker scale.  For children over 5 years and adults use visual numeric pain scale','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Leg Length Discrepancy (LLD) " and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'using measuring tape','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip abduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip abduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip adduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip adduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip int. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip int. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Hip ext. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Hip ext. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Knee flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Knee flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Knee extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Knee extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Ankle dorsiflex." and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Ankle dorsiflex." and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Ankle planterflex" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Ankle planterflex" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Ankle inversion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Ankle inversion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Ankle eversion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Ankle eversion " and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Balance Score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Sum of balance section','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Indication of gait" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Immediately after told to "go"','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Gait Score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Sum of gait section','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Total Score Tinetti Balance Assessment Tool" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Balance + Gait score','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Risk of falls " and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Risk indicator','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder abduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder abduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder adduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder adduction" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder int. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder int. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Shoulder ext. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Shoulder ext. rotation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Elbow flexion " and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Elbow flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Elbow extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Elbow extension " and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Forearm pronation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Forearm pronation" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Forearm supination" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Forearm supination" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Wrist flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Wrist flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Wrist extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Wrist extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Distance tip (2nd -5th)" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  cm','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Distance tip (Thumb - 2nd)" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  cm','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : Thumb MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : Thumb MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : Thumb DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : Thumb DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 2nd Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 2nd Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 3rd Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 3rd Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 4th Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 4th Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 5th Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 5th Finger MC" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 2nd Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 2nd Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 3rd Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 3rd Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 4th Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 4th Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 5th Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 5th Finger PIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 2nd Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 2nd Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 3rd Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 3rd Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 4th Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 4th Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Flex : 5th Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Ext : 5th Finger DIP" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Chuck or three-fingered pinch" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Pinch grip with thumb and next two fingers (index and middle finger), MCPs flexed, DIPs and PIPs almost extended. Examples: Holding a pen or pencil.','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Cylindrical grasp" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'All fingers flexed around the object, thumb wrapped around object in opposite direction. Examples: Holding a can, a brush handle, a hammer.','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Spherical" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'All fingers and thumb adducted around an object, fingers more spread apart, palm often not involved. Examples: holding a ball, opening a jar, turning a doorknob, holding an apple, picking up a glass by its top.','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Hook" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Two or more fingers are wrapped around an object in a hook-like manner.Examples: Lifting a bucket with the handle, carrying purse or briefcase','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Tip pinch (or tip to tip prehension)" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Tip of the thumb has contact to the tip of another digit (most common it is the index), to pick up small objects. Examples: Pen, pin, coin','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Lateral or key pinch" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Pad of extended thumb is pressing an object against the radial side of the index. MCP and PIP of the fingers are flexed, thumb abducted and distal joints extended, bringing pads of the finger and thumb together.Examples: Card holding, turning a key, pulling a document out of an envelope etc.','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Basic grip test, total score" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'Sum columns for total (out of 12)','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Big toe flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Big toe extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Big toe flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Big toe extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Fingers flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Fingers flexion" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Left : Fingers extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "PA, Right : Fingers extension" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),'units:  degrees','en',1,now(),NULL,NULL,uuid());
