- name: Find existing visit-close-module omod
  find:
    paths: /opt/openmrs/modules
    patterns: visit-close-module*.omod
  register: result

- name: Delete visit-close-module omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get visit-close-module omod from s3 bucket and place it in /opt/openmrs/modules
  get_url:
    url: "{{ visitclosemodule }}"
    dest: /opt/openmrs/modules/visit-close-module.omod
    mode: 0644

- name: Change ownership of bahmni.ie.apps file
  action: file state=file path=/opt/openmrs/modules/visit-close-module.omod owner=bahmni group=bahmni
