- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: appointments, tags: appointments }
    - { role: bahmni-core, tags: bahmni-core }
    - { role: bahmni-ie-apps, tags: bahmni-ie-apps }
    - { role: bahmni-apps, tags: bahmni-apps }
    - { role: implementer-interface, tags: implementer-interface }
    - { role: appointment-frontend, tags: appointment-frontend }
