- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: appointments, tags: appointments }
    - { role: bahmni-core, tags: bahmni-core }
    - { role: bahmni-ie-apps, tags: bahmni-ie-apps }
    - { role: bahmni-apps, tags: bahmni-apps }
    - { role: implementer-interface, tags: implementer-interface }
    - { role: appointment-frontend, tags: appointment-frontend }
    - { role: openmrs-ui-framework, tags: openmrs_ui_framework }
    - { role: emr-api-omod, tags: emr-api-omod }
    - { role: event-omod, tags: event-omod }
    - { role: visit-close-module, tags: visit_close_module }
    - { role: patient-identifier-generator, tags: patient_identifier_generator }
