implementerinterface: https://bahmni-msf.s3.ap-south-1.amazonaws.com/iraq-release-artifacts/release-1.2/bahmni-implementer-interface-91.noarch.rpm
bahmniapps: https://form2-artifacts-on-bahmni-91-release.s3.ap-south-1.amazonaws.com/bahmniapps/bahmniapps.zip
appointments: https://bahmni-msf.s3.ap-south-1.amazonaws.com/iraq-release-artifacts/release-1.1/appointments.omod
bahmnicore: https://s3.ap-south-1.amazonaws.com/bahmni-msf/iraq-release-artifacts/release-1.0/bahmnicore-0.92-SNAPSHOT.omod
bahmniieapps: https://bahmni-msf.s3.ap-south-1.amazonaws.com/iraq-release-artifacts/release-1.2/bahmni.ie.apps-0.92.omod
visitclosemodule: https://bahmni-msf.s3.ap-south-1.amazonaws.com/iraq-release-artifacts/release-1.2/visit-close-module-0.91.omod



