set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

-- Adding concepts sets to openmrs

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSEUDOMONAS SPP.","PSEUDOMONAS SPP.","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"STREPTOCOCCUS SPP (Group A, B, C, G)","STREPTOCOCCUS SPP (Group A, B, C, G)","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ENTEROBACTERIA","ENTEROBACTERIA","N/A","Misc",true);
-- call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology Results","Results","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Final Identification Section","Final Identification","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ACINETOBACTER SP","ACINETOBACTER SP","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"STAPHYLOCOCCUS AUREUS","STAPHYLOCOCCUS AUREUS","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"COAGULASE NEGATIVE STAPHYLOCOCCI","COAGULASE NEGATIVE STAPHYLOCOCCI","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"STREPTOCOCCUS PNEUMONIAE Section","STREPTOCOCCUS PNEUMONIAE","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"STREPTOCOCCUS VIRIDANS","STREPTOCOCCUS VIRIDANS","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ENTEROCOCCUS SPP","ENTEROCOCCUS SPP","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HAEMOPHILUS INFLUENZAE Section","HAEMOPHILUS INFLUENZAE","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NEISSERIA MENINGITIDIS Section","NEISSERIA MENINGITIDIS","N/A","Misc",true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NEISSERIA GONORRHOEAE Section","NEISSERIA GONORRHOEAE","N/A","Misc",true);

-- Adding Parent concepts
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Results, Growth","Growth","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Results, Comments, no growth","Comments, no growth","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"FI, Final identification","Final identification","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Ampicillin","Ampicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Amoxicillin and clavulanic acid","Amoxicillin and clavulanic acid","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Piperacillin - tazobactam","Piperacillin - tazobactam","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Cefoxitin","Cefoxitin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Ceftazidime","Ceftazidime","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Imipenem","Imipenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Meropenem","Meropenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Gentamicin","Gentamicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Amikacin","Amikacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Colistin MIC","Colistin MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"EB, Tigecycline MIC","Tigecycline MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Piperacillin - tazobactam","Piperacillin - tazobactam","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Ceftazidime","Ceftazidime","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Gentamicin","Gentamicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Amikacin","Amikacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Imipenem","Imipenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Meropenem","Meropenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"PSP, Colistin MIC","Colistin MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Piperacillin - tazobactam","Piperacillin - tazobactam","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Ceftazidime","Ceftazidime","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Gentamicin","Gentamicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Amikacin","Amikacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Imipenem","Imipenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Meropenem","Meropenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"AS, Colistin MIC","Colistin MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Penicillin","Penicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Cefoxitin","Cefoxitin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Gentamicin","Gentamicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Clindamycin","Clindamycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Vancomycin MIC","Vancomycin MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SA, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Penicillin","Penicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Cefoxitin","Cefoxitin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Oxacillin","Oxacillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Gentamicin","Gentamicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Clindamycin","Clindamycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Vancomycin MIC","Vancomycin MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"CNS, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Penicillin","Penicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Clindamycin","Clindamycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SSP, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Oxacillin","Oxacillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Clindamycin","Clindamycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SP, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SV, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SV, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SV, Clindamycin","Clindamycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SV, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"SV, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Penicillin","Penicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Ampicillin","Ampicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Erythromycin","Erythromycin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESP, Linezolid MIC","Linezolid MIC","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Ampicillin","Ampicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Augmentin","Augmentin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Piperacillin - tazobactam","Piperacillin - tazobactam","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Ceftazidime","Ceftazidime","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Imipenem","Imipenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Meropenem","Meropenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Ciprofloxacine","Ciprofloxacine","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"HI, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NM, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NM, Meropenem","Meropenem","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NM, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NM, Trimethoprim - sulfamethoxazole","Trimethoprim - sulfamethoxazole","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NM, Rifampicin","Rifampicin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Penicillin","Penicillin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Ceftriaxone","Ceftriaxone","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Cefoxitin","Cefoxitin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Ceftazidime","Ceftazidime","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Ciprofloxacin","Ciprofloxacin","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"NG, Tetracycline","Tetracycline","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Comments","Comments","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Are there any alerts?","Are there any alerts?","Coded","Question",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Alerts","Alerts","Coded","Question",false);

-- Adding child Concepts.



call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Growth","Growth","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"No growth","No growth","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter baumannii","Acinetobacter baumannii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter nosocomialis","Acinetobacter nosocomialis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter pittii","Acinetobacter pittii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter dijkshoorniae","Acinetobacter dijkshoorniae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter seifertii","Acinetobacter seifertii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter haemolyticus","Acinetobacter haemolyticus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter junii","Acinetobacter junii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter lwoffii","Acinetobacter lwoffii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter ursingii","Acinetobacter ursingii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Acinetobacter variabilis","Acinetobacter variabilis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Bacteroides fragilis","Bacteroides fragilis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Burkholderia cepacia","Burkholderia cepacia","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Campylobacter coli","Campylobacter coli","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Campylobacter jejuni ss. jejuni","Campylobacter jejuni ss. jejuni","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Candida albicans","Candida albicans","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Citrobacter freundii","Citrobacter freundii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Corynebacterium sp. (diphtheroids)","Corynebacterium sp. (diphtheroids)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterobacter aerogenes","Enterobacter aerogenes","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterobacter cloacae","Enterobacter cloacae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus avium","Enterococcus avium","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus faecalis","Enterococcus faecalis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus faecium","Enterococcus faecium","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus sp.","Enterococcus sp.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus casseliflavus","Enterococcus casseliflavus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus durans","Enterococcus durans","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus gallinarum","Enterococcus gallinarum","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus hirae","Enterococcus hirae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus mundtii","Enterococcus mundtii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Enterococcus raffinosus","Enterococcus raffinosus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Escherichia coli","Escherichia coli","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Escherichia coli O157:H7","Escherichia coli O157:H7","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Haemophilus influenzae","Haemophilus influenzae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Haemophilus influenzae (non type b)","Haemophilus influenzae (non type b)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Haemophilus influenzae (type b)","Haemophilus influenzae (type b)","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Klebsiella oxytoca","Klebsiella oxytoca","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Klebsiella pneumoniae ss. pneumoniae","Klebsiella pneumoniae ss. pneumoniae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Listeria monocytogenes","Listeria monocytogenes","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Mixed bacterial species present","Mixed bacterial species present","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Moraxella (Branh.) catarrhalis","Moraxella (Branh.) catarrhalis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Morganella morganii ss. morganii","Morganella morganii ss. morganii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Mycobacterium avium-intracellulare complex","Mycobacterium avium-intracellulare complex","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Mycobacterium tuberculosis","Mycobacterium tuberculosis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Neisseria gonorrhoeae","Neisseria gonorrhoeae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Neisseria meningitidis","Neisseria meningitidis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Normal flora","Normal flora","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Oral flora","Oral flora","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Proteus mirabilis","Proteus mirabilis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pseudomonas aeruginosa","Pseudomonas aeruginosa","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pseudomonas fluorescens","Pseudomonas fluorescens","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pseudomonas putida","Pseudomonas putida","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Pseudomonas stutzeri","Pseudomonas stutzeri","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Raoultella spp","Raoultella spp","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Salmonella enteritidis","Salmonella enteritidis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Salmonella sp.","Salmonella sp.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Salmonella typhi","Salmonella typhi","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Salmonella typhimurium","Salmonella typhimurium","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Serratia marcescens","Serratia marcescens","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Shigella boydii","Shigella boydii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Shigella boydii serotype 1","Shigella boydii serotype 1","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus aureus ss. aureus","Staphylococcus aureus ss. aureus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus epidermidis","Staphylococcus epidermidis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus haemolyticus","Staphylococcus haemolyticus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus lugdunensis","Staphylococcus lugdunensis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus pseudintermedius","Staphylococcus pseudintermedius","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus schleiferi","Staphylococcus schleiferi","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus saprophyticus ss. saprophyticus","Staphylococcus saprophyticus ss. saprophyticus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus capitis","Staphylococcus capitis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus cohnii","Staphylococcus cohnii","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus hominis","Staphylococcus hominis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus hyicus","Staphylococcus hyicus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcus, coagulase negative","Staphylococcus, coagulase negative","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Stenotrophomonas maltophilia","Stenotrophomonas maltophilia","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus pneumoniae","Streptococcus pneumoniae","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus salivarius","Streptococcus salivarius","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus viridans, alpha-hem","Streptococcus viridans, alpha-hem","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus mutans","Streptococcus mutans","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus bovis","Streptococcus bovis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus anginosus","Streptococcus anginosus","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus mitis","Streptococcus mitis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus sanguinis","Streptococcus sanguinis","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus, beta-haem. Group A","Streptococcus, beta-haem. Group A","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Streptococcus, beta-haem. Group B","Streptococcus, beta-haem. Group B","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Susceptible","Susceptible","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Resistant","Resistant","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Intermediate","Intermediate","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Susceptible isolates are uncommon. Check for a possible laboratory error.","Susceptible isolates are uncommon. Check for a possible laboratory error.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Non-susceptible isolates are rare. Check for a possible laboratory error.","Non-susceptible isolates are rare. Check for a possible laboratory error.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Non-susceptible isolates are rare.","Non-susceptible isolates are rare.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"The isolate is resistant to all tested antibiotics. You may wish to send the isolate to a reference laboratory for additional testing.","The isolate is resistant to all tested antibiotics. You may wish to send the isolate to a reference laboratory for additional testing.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"This is an uncommon resistance pattern. Check for a possible laboratory error.","This is an uncommon resistance pattern. Check for a possible laboratory error.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"This is an important species. Report to relevant public health authorities if appropriate.","This is an important species. Report to relevant public health authorities if appropriate.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disk diffusion results are not reliable for this organism and antibiotic.","Disk diffusion results are not reliable for this organism and antibiotic.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Depending on your area, resistant isolates may be uncommon.","Depending on your area, resistant isolates may be uncommon.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"This is an uncommon resistant pattern. The organism may possess the aac 6'1 enzyme.","This is an uncommon resistant pattern. The organism may possess the aac 6'1 enzyme.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"ESBL-producing Enterobacteriaceae should be reported as resistant for all penicillins, aztreonam, and cephalosporins, with the exception of cephamycins.","ESBL-producing Enterobacteriaceae should be reported as resistant for all penicillins, aztreonam, and cephalosporins, with the exception of cephamycins.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Test for the presence of a carbapenemase.","Test for the presence of a carbapenemase.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Rare beta-lactamase-negative, ampicillin-resistant (BLNAR) strains of H. influenzae should be considered resistant to amoxicillin-clavulanic acid, ampicillin-sulbactam, cefaclor, cefetamet, cefonicid, cefprozil, cefuroxime, and loracarbef.","Rare beta-lactamase-negative, ampicillin-resistant (BLNAR) strains of H. influenzae should be considered resistant to amoxicillin-clavulanic acid, ampicillin-sulbactam, cefaclor, cefetamet, cefonicid, cefprozil, cefuroxime, and loracarbef.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Non-susceptible isolates have not been previously identified.","Non-susceptible isolates have not been previously identified.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Trimethoprim/sulfamethoxazole is the preferred disk for detection of sulfonamid resistance with N. meningitidis.","Trimethoprim/sulfamethoxazole is the preferred disk for detection of sulfonamid resistance with N. meningitidis.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"The susceptibility of P. aeruginosa isolated from patients with cystic fibrosis can be reliably determined by the disk method, but may require extended incubation up to 24 hours before reporting as susceptible.","The susceptibility of P. aeruginosa isolated from patients with cystic fibrosis can be reliably determined by the disk method, but may require extended incubation up to 24 hours before reporting as susceptible.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Oxacillin-resistant isolates should be considered resistant to all beta-lactam agents.","Oxacillin-resistant isolates should be considered resistant to all beta-lactam agents.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Isolates of staphylococci that carry the mecA gene or that produce PBP2a should be reported as oxacillin resistant. Oxacillin-resistant isolates should be considered resistant to all beta-lactam agents.","Isolates of staphylococci that carry the mecA gene or that produce PBP2a should be reported as oxacillin resistant. Oxacillin-resistant isolates should be considered resistant to all beta-lactam agents.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"For S. lugdunensis, only the cefoxitin disk should be used.","For S. lugdunensis, only the cefoxitin disk should be used.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Check for inducible clindamycin resistance.","Check for inducible clindamycin resistance.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"The cefoxitin disk test is the preferred method for testing staphylococci for oxacillin resistance.","The cefoxitin disk test is the preferred method for testing staphylococci for oxacillin resistance.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Staphylococcal isolates which appear 'non-susceptible' by disk diffusion should be confirmed by MIC testing.","Staphylococcal isolates which appear 'non-susceptible' by disk diffusion should be confirmed by MIC testing.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"For strains of S. pneumoniae appearing non-susceptible by disk diffusion, you should perform an MIC test for penicillin, meropenem, cefotaxime, and/or ceftriaxone.","For strains of S. pneumoniae appearing non-susceptible by disk diffusion, you should perform an MIC test for penicillin, meropenem, cefotaxime, and/or ceftriaxone.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Disk diffusion results may not be reliable for this organism and antibiotic.","Disk diffusion results may not be reliable for this organism and antibiotic.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Isolates may develop resistance during therapy. Testing of repeat isolates may be warranted.","Isolates may develop resistance during therapy. Testing of repeat isolates may be warranted.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"These agents may appear susceptible in vitro but are not effective clinically.","These agents may appear susceptible in vitro but are not effective clinically.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Rifampin should not be used alone for chemotherapy.","Rifampin should not be used alone for chemotherapy.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Breakpoints presume that clarithromycin will be used in an approved regimen that includes a proton-pump inhibitor or an H2 antagonist.","Breakpoints presume that clarithromycin will be used in an approved regimen that includes a proton-pump inhibitor or an H2 antagonist.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"N. gonorrhoeae isolates with intermediate results with most agents have a documented lower clinical cure rate (85 to 95%) compared to >95% for susceptible strains. For cefmetazole, cefotetan, cefoxitin, and spectinomycin, the impact is unclear.","N. gonorrhoeae isolates with intermediate results with most agents have a documented lower clinical cure rate (85 to 95%) compared to >95% for susceptible strains. For cefmetazole, cefotetan, cefoxitin, and spectinomycin, the impact is unclear.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"A nalidixic acid zone<=25mm may correlate with diminished fluoroquinolone susceptibility.","A nalidixic acid zone <=25mm may correlate with diminished fluoroquinolone susceptibility.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"A nalidixic acid MIC >=8 ug/ml may correlate with diminished fluoroquinolone susceptibility.","A nalidixic acid MIC >=8 ug/ml may correlate with diminished fluoroquinolone susceptibility.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Azithromycin, minocycline, ciprofloxacin, sulfonamides, and rifampin may be appropriate only for prophylaxis of meningococcal case contacts. Breakpoints do not apply to therapy of patients with invasive meningococcal disease.","Azithromycin, minocycline, ciprofloxacin, sulfonamides, and rifampin may be appropriate only for prophylaxis of meningococcal case contacts. Breakpoints do not apply to therapy of patients with invasive meningococcal disease.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fluoroquinolone-susceptible strains for Salmonella that test resistant to nalidixic acid may be associated with clinical failure or delayed response in patients with extraintestinal salmonellosis.","Fluoroquinolone-susceptible strains for Salmonella that test resistant to nalidixic acid may be associated with clinical failure or delayed response in patients with extraintestinal salmonellosis.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Routine testing of urine isolates of S. saprophyticus is not advised, because infections respond to concentrations achieved in urine of antimicrobial agents commonly used to treat acute, uncomplicated urinary tract infections.","Routine testing of urine isolates of S. saprophyticus is not advised, because infections respond to concentrations achieved in urine of antimicrobial agents commonly used to treat acute, uncomplicated urinary tract infections.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"This isolate is presumed to be resistant based on detection of inducible clindamycin resistance. Clindamycin may still be effective in some patients.","This isolate is presumed to be resistant based on detection of inducible clindamycin resistance. Clindamycin may still be effective in some patients.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"High doses of intravenous penicillins or ampicillin are effective in treating pneumococcal pneumonia due to strains in the intermediate category.","High doses of intravenous penicillins or ampicillin are effective in treating pneumococcal pneumonia due to strains in the intermediate category.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Use of interpretive criteria for non-meningitis requires doses appropriate for serious pneumococcal infections.","Use of interpretive criteria for non-meningitis requires doses appropriate for serious pneumococcal infections.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Use of cefotaxime or ceftriaxone in meningitis requires therapy with maximum doses.","Use of cefotaxime or ceftriaxone in meningitis requires therapy with maximum doses.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Penicillin or ampicillin intermediate isolates may require combined therapy with an aminoglycoside for bactericidal action.","Penicillin or ampicillin intermediate isolates may require combined therapy with an aminoglycoside for bactericidal action.","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Recommendations for intrapartum prophylaxis for Group B streptococci are penicillin or ampicillin. When a Group B streptococcus is isolated from a pregnant woman with severe penicillin allergy, clindamycin and erythromycin should be tested and report","Recommendations for intrapartum prophylaxis for Group B streptococci are penicillin or ampicillin. When a Group B streptococcus is isolated from a pregnant woman with severe penicillin allergy, clindamycin and erythromycin should be tested and report","N/A","Misc",false);

-- Add concepts for Bacteriology Tab

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Volume of collected blood","Volume of collected blood","Numeric","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Last CRP","Last CRP","Text","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Sample description","Sample description","Text","Misc",false);

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Bone and Tissue","Bone and Tissue","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Swab","Swab","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Midstream urine","Midstream urine","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, CSF","CSF","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Blood Culture","Blood Culture","N/A","Misc",false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Microbiology, Aspirate","Aspirate","N/A","Misc",false);


INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "Microbiology, Volume of collected blood" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"Only fill if type of sample is blood culture",'en',1,now(),NULL,NULL,uuid());
INSERT INTO concept_description (concept_id,description,locale,creator,date_created,changed_by,date_changed,uuid) VALUES ((select concept_id from concept_name where name = "Microbiology, Sample description" and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0),"Specify location and specimen description",'en',1,now(),NULL,NULL,uuid());

INSERT INTO concept_numeric (concept_id,hi_absolute,hi_critical,hi_normal,low_absolute,low_critical,low_normal,units,precise,display_precision)
VALUES ((select concept_id from concept_name where name = "Microbiology, Volume of collected blood" and concept_name_type = 'FULLY_SPECIFIED'  and locale = 'en' and voided = 0),NULL,NULL,NULL,NULL,NULL,NULL,"",1,1);
