set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept(@concept_id,@concept_short_id,@concept_full_id,'New assessment','New assessment','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Re-assessment','Re-assessment','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Abu Ghraib Hospital','Abu Ghraib Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Furat Hospital','Al Furat Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Kadhmiya Hospital','Al Kadhmiya Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Karkh Hospital','Al Karkh Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Kindi Hospital','Al Kindi Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Mahmoudia Hospital','Al Mahmoudia Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Sheikh Zaed Hospital','Al Sheikh Zaed Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Wasity Hospital','Al Wasity Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Al Yarmouk Hospital','Al Yarmouk Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Imam Ali Hospital','Imam Ali Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Medical City Specialty Hospital','Medical City Specialty Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Numan Hospital','Numan Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Shaheed Sadr Hospital','Shaheed Sadr Hospital','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Amman MSFF RSP','Amman MSFF RSP','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Assault','Assault','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Bomb Blast','Bomb Blast','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Mine','Mine','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Fall','Fall','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Gun Shot','Gun Shot','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Torture','Torture','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Other, violence related','Other, violence related','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Road Traffic Accident','Road Traffic Accident','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Other, non-violence related','Other, non-violence related','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Internal','Internal','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'External','External','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Amputation','Amputation','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Upper Limb Fracture, initially closed','Upper Limb Fracture, initially closed','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Upper Limb Fracture, initially open','Upper Limb Fracture, initially open','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Femoral Fracture, initially closed','Femoral Fracture, initially closed','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Femoral Fracture, initially open','Femoral Fracture, initially open','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Lower Leg Fracture, initially open','Lower Leg Fracture, initially open','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Lower Leg Fracture, initially closed','Lower Leg Fracture, initially closed','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Traumatic amputation, below knee','Traumatic amputation, below knee','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Traumatic amputation, above knee','Traumatic amputation, above knee','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Traumatic amputation at knee level','Traumatic amputation at knee level','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Traumatic bilateral lower limbs amputation','Traumatic bilateral lower limbs amputation','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Pelvic fracture','Pelvic fracture','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Patella fracture','Patella fracture','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Multiple lower limb fractures','Multiple lower limb fractures','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade I','Grade I','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade II','Grade II','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade III','Grade III','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade IIIA','Grade IIIA','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade IIIB','Grade IIIB','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Grade IIIC','Grade IIIC','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Associated peripheral nerve injury','Associated peripheral nerve injury','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Associated 1st degree or minor 2nd degree burn','Associated 1st degree or minor 2nd degree burn','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Limb amputation','Limb amputation','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Need for dressing, pain management','Need for dressing, pain management','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Other associated injury or condition','Other associated injury or condition','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Walking alone','Walking alone','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Crutches','Crutches','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Walking frame','Walking frame','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Walking','Walking','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Wheelchair','Wheelchair','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Bedridden','Bedridden','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Independent','Independent','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'With aid','With aid','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Dependent','Dependent','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'No WB','No WB','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Partial WB','Partial WB','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Full WB','Full WB','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'As tolerated','As tolerated','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Pain management','Pain management','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Nursing care','Nursing care','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Joint mobilization','Joint mobilization','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Muscle strengthening','Muscle strengthening','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Date of Assessment','Date of Assessment','Date','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Type of assessment','Type of assessment','Coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Hospital of Origin','Hospital of Origin','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Other Hospital of Origin','Other Hospital of Origin','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Treating Surgeon','Treating Surgeon','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'History of present illness (context)','History of present illness (context)','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Date of injury','Date of injury','date','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Cause of injury','Cause of injury','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'None','None','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'No','No','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Yes','Yes','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Unknown','Unknown','N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Date of last surgery','Date of last surgery','date','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Type of fixation','Type of fixation','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Presumed diagnosis','Presumed diagnosis','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Gustilo classification of fractures','Gustilo classification of fractures','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Associated injuries and need','Associated injuries and need','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Other associated injury or condition, comments','Other associated injury or condition, comments','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Prophylactic antibiotics','Prophylactic antibiotics','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Specify prophylactic antibiotic','Specify prophylactic antibiotic','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Examination of injured area','Examination of injured area','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Patient mobility','Patient mobility','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Bed to wheelchair transfer','Bed to wheelchair transfer','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Sitting position','Sitting position','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Weight-bearing status','Weight-bearing status','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Physiotherapy before assessment','Physiotherapy before assessment','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Physiotherapy, comments','Physiotherapy, comments','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Current treatment in orthopedic ward','Current treatment in orthopedic ward','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Anti-tetanus vaccination status','Anti-tetanus vaccination status','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Care requested for this patient','Care requested for this patient','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Weight-bearing recommendation','Weight-bearing recommendation','coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Joint authorized range of motion mobilization','Joint authorized range of motion mobilization','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Any contraindications to care requested','Any contraindications to care requested','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'General notes and comments','General notes and comments','text','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Patient video','Patient video','Complex','Video',false);

call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Clinical Examination','Clinical Examination','N/A','Misc',true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Physiotherapy Preassessment','Physiotherapy Preassessment','N/A','Misc',true);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,'Requested care','Requested care','N/A','Misc',true);
